### ISSUE TITLE
Print layout broken

### ISSUE THREAD

**Issue by dirk-zimoch** [epics-base/website#8]
The whole layout is broken when trying to print one of the web pages.

The first page contains the menu (which is totally useless in a hardcopy)
The second page contains all the content but is clipped to one page (you cannot scroll a hardcopy!)
The third page contains the footer.

It seems printing has never been thought of and was never tested.
Consider using @print CSS rules.

**Comment by ttkorhonen** [comment]
Print layouts should now work, in cases when there is something worth printing on the pages. Please report if there are still problems.

**Comment by ralphlange** [comment]
@dirk-zimoch, I think this issue has been fixed.
Please check again, and close the issue if you think it is good enough now.

**Comment by dirk-zimoch** [comment]
There is still a problem in  the "Projects" page:
Page 1 only shows the header and logo but no projects. Page 2 shows the first 12 projects. It also shows a "Top" scroll button, which should not appear in a hardcopy.
Page 3 only contains a "Load more" button.

Thus I still consider the Projects page "unprintable".

**Comment by dirk-zimoch** [comment]
On the "EPICS Users" page the text appears above the image in the left column. The text is clipped with the first 2 letters of every line missing.The right column is empty.
A second page is printed but is empty.

**Comment by dirk-zimoch** [comment]
The "New and Events" shows only a clipped logo image and some funny ] shaped greenish markers on the first print page. The rest of the print pages with the event list look fine.

**Comment by dirk-zimoch** [comment]
Can I add images in this tracker to show the layout problems?

**Comment by ttkorhonen** [comment]
I have not figured out how one could add images, maybe the more experienced users can help.
However, I think that the issues are clear. It was also clear to us that there are some remaining issues; being time-limited we concentrated on fixing the layout on pages that (we thought) would be the most useful to print. Those being mainly on the documentation pages.
If somebody wants to pick up this ticket and fix the remaining problems it would be welcome. From our (ESS) side I am afraid it will be a while before we can get back to this issue, sorry.

**Comment by ralphlange** [comment]
I think files (images) can be dragged'n'dropped into the box, can't they?

**Comment by ttkorhonen** [comment]
You are right, never tried that. But the issues are clear also without the images in this case.

**Comment by anjohnson** [comment]
Pasting an image into the comment box also works:
![image](https://user-images.githubusercontent.com/5453863/45968475-b5566c00-bff6-11e8-972c-712fcc5d75b6.png)

**Comment by dirk-zimoch** [comment]
![epics-users-layout-problem](https://user-images.githubusercontent.com/12862431/45999540-3f114280-c0a6-11e8-8331-c60fd16d9149.gif)
Text is clipped.

**Comment by dirk-zimoch** [comment]
![epics-news-layout-problem](https://user-images.githubusercontent.com/12862431/45999700-b0e98c00-c0a6-11e8-9d6a-e4092313e452.gif)
Page is almost empty except for some ] markers.

**Comment by keijokorhonen** [comment]
Unfortunately the plugins we use to display the News and Events as well as the projects make it hard to display their content for printing. It seems like the plugins load only a part of the content, which can't be fixed using only css media print rules. The pages look fine when I emulate media print in Firefox, but the print itself is broken. 

A workaround for the News and Events page would be to print the RSS feed, which seems to work much better. I am at a loss for projects however. Single projects print out fine though.
